# -*- coding: utf-8 -*-
"""joguinho teste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150xSt7OsP_ZBLNBN8isHynBJoL6EXwqY
"""

import os

jogador = {"nome":"Phyton", "x":0,"y":0}

def movimento(direcao):
  if direcao=="d":
    jogador['x'] +=1
  if direcao=="a":
    jogador['x'] -=1
  if direcao=="w":
    jogador['y'] -=1
  if direcao=="s":
    jogador['y'] +=1

while True:
  os.system('clear')
  print("---------------------------")
  for y in range(5):
    print("\n")
    for x in range(10):
      if jogador['x'] == x and jogador['y'] == y:
        print("🐉", end="")
      else:
        print("⬛", end="")
  print("--------------------------")

  direcao = input("insira a direçãoa(w,a,s,d)")
  movimento(direcao)